name: hello4

on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
         

      - name: say hello3
        run: echo 'say hello3' 
        
  build-api:
    needs: builds  
    runs-on: ubuntu-latest
    steps:
      run: echo "testing the needs build last step"
